modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "creategears"
version = "${mod_version}"
displayName = "Create Gears"
description = '''Shaftless gears for Create! A port of Create: Gears n' Kinetics to Create 0.5.1 / Forge 1.20.1.'''
authors = "Ra1T0r"

[[dependencies.creategears]]
modId = "forge"
mandatory = true
versionRange = "[${forge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.creategears]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.creategears]]
modId = "create"
mandatory = true
versionRange = "[0.5.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.creategears]]
modId = "flywheel"
mandatory = true
versionRange = "[0.6.0,0.7)"
ordering = "AFTER"
side = "CLIENT"
